language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE vineyardstest;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: JDcqno1u8dRgqnGZwzrCT1rVd/1HkIbGvqR9iY8pseSyDOAU56VZ0/jdG4yze5ChdAD55GOFhlWxjtGWiAxyZMRoUai0szY0rz7IDauc4zQ1XtEqxkoyIig2+ZsdWhvWUIdt7ia9I8dm8O6Ry6pqBk2TPNXlyypM+/wzjoiza9sxepWWOdRE+JtfMuUBbviq0smWddJcnW6l7SRW/TaJuOa6KaNup+yB5ZooILqC+ZBJ73ot0GqXcEnYlyIdzgztAI/y3Y/q3xr/Dhmj9YVBYl4/FT5yy/cNERRQXXZUYrKvdQNQd5lSrzBWCPtNbvkjRm/dRRdJs2AUA+g5AZY3TYOeekuP0mI7QcAqtRNeamuxchRNM+kyJArJzJcriTTDQVeEWyLzKJsUud3n2pQ21UAELXGCbjbXbJpTPRGC8wEY/ow0cMBZbtMinmq6sRCaS7AeiwBtfvr36zJ73BrdXYyxg6kdu7xsszKRlZwVaI2uXywwyxBPbZFveEf7HYp6uuOjB1PiqU0VPB/aKFafDI1fG6fRNSoIKC+fo6RBBYX24UnYchbeV9a/kcEV78etzHs9AoQpShNMiOXw4iw4IWWx390d7J262Fi/EIfHPpnkMHqAClsPbSH6UtQq9AyfEZuIErpskfWExYR2UuKZWJ3L7h9gMT4R0HXtaBPq9Go=
  app: buildyourownbackendcodysara
  on: 
  repo: Cody-Price/BYOB
  skip_cleanup: true
scripts:
  start: node server.js
  test: NODE_ENV=test jest --exit
